# Generated by Django 4.2 on 2023-04-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Glucose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PatientId", models.CharField(max_length=100)),
                ("GlucoseDisplayTime", models.DateTimeField()),
                ("Value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GlucoseFull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PatientId", models.CharField(max_length=100)),
                ("Value", models.IntegerField()),
                ("PostDate", models.DateField()),
                ("IngestionDate", models.DateField()),
                ("PostId", models.CharField(max_length=100)),
                ("PostTime", models.DateTimeField()),
                ("Stream", models.CharField(max_length=100)),
                ("SequenceNumber", models.IntegerField()),
                ("TransmitterNumber", models.CharField(max_length=100)),
                ("ReceiverNumber", models.CharField(max_length=100)),
                ("RecordedSystemTime", models.DateTimeField()),
                ("RecordedDisplayTime", models.DateTimeField()),
                ("RecordedDisplayTimeRaw", models.DateTimeField()),
                ("TransmitterId", models.CharField(max_length=100)),
                ("TransmitterTime", models.IntegerField()),
                ("GlucoseSystemTime", models.DateTimeField()),
                ("GlucoseDisplayTime", models.DateTimeField()),
                ("GlucoseDisplayTimeRaw", models.DateTimeField()),
                ("Status", models.CharField(max_length=100)),
                ("TrendArrow", models.CharField(max_length=100)),
                ("TrendRate", models.FloatField()),
                ("IsBackFilled", models.BooleanField()),
                ("InternalStatus", models.IntegerField()),
                ("SessionStartTime", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GlucoseRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PatientId", models.CharField(max_length=100)),
                ("Value", models.IntegerField()),
                ("PostDate", models.CharField(max_length=100)),
                ("IngestionDate", models.DateField()),
                ("PostId", models.CharField(max_length=100)),
                ("PostTime", models.DateTimeField()),
                ("Stream", models.CharField(max_length=100)),
                ("SequenceNumber", models.IntegerField()),
                ("TransmitterNumber", models.CharField(max_length=100)),
                ("ReceiverNumber", models.CharField(max_length=100)),
                ("RecordedSystemTime", models.CharField(max_length=100)),
                ("RecordedDisplayTime", models.CharField(max_length=100)),
                ("RecordedDisplayTimeRaw", models.CharField(max_length=100)),
                ("TransmitterId", models.CharField(max_length=100)),
                ("TransmitterTime", models.IntegerField()),
                ("GlucoseSystemTime", models.CharField(max_length=100)),
                ("GlucoseDisplayTime", models.CharField(max_length=100)),
                ("GlucoseDisplayTimeRaw", models.CharField(max_length=100)),
                ("Status", models.CharField(max_length=100)),
                ("TrendArrow", models.CharField(max_length=100)),
                ("TrendRate", models.FloatField()),
                ("IsBackFilled", models.BooleanField()),
                ("InternalStatus", models.IntegerField()),
                ("SessionStartTime", models.IntegerField()),
            ],
        ),
    ]
